In [216]:
import numpy as np

# 1.Data Types & attributes

numpy's main and only datatype is ndarray

ndarray: N demension array

In [217]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [218]:
type(a1)

numpy.ndarray

In [219]:
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [220]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [221]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## 2.Atributes

In [222]:
a1.shape

(3,)

In [223]:
a1

array([1, 2, 3])

In [224]:
a2.shape

(2, 3)

In [225]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [226]:
a3.shape

(2, 3, 3)

In [227]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [228]:
a1.ndim, a2.ndim, a3.ndim # ndim for the number of dimension

(1, 2, 3)

In [229]:
a1.dtype, a2.dtype, a3.dtype # dtype for the datatype 

(dtype('int32'), dtype('float64'), dtype('int32'))

In [230]:
a1.size, a2.size, a3.size # size for the number of elements

(3, 6, 18)

In [231]:
type(a1), type(a2), type(a3) # type() for the type of the variable  

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# 2.Created DataFrame from NumPy array

In [232]:
import pandas as pd

In [233]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [234]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2.Creating arrays

In [235]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [236]:
sample_array.dtype

dtype('int32')

In [237]:
ones = np.ones((2,3))

In [238]:
ones.dtype

dtype('float64')

In [239]:
type(ones)

numpy.ndarray

In [240]:
zeros = np.zeros((2,3))

In [241]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [242]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [243]:
random_array = np.random.randint(0,10, size=(3,5))

In [244]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [245]:
random_array.size

15

In [246]:
random_array.shape

(3, 5)

In [247]:
random_array_2 = np.random.random((5,3)) * 100

In [248]:
random_array_2

array([[79.91585642, 46.14793623, 78.05291763],
       [11.82744259, 63.99210213, 14.33532874],
       [94.4668917 , 52.18483218, 41.466194  ],
       [26.45556121, 77.42336894, 45.61503322],
       [56.84339489,  1.87898004, 61.76354971]])

In [249]:
random_array_3 = np.random.rand(5,3)

In [250]:
random_array_3

array([[0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677]])

Pesudo-random numebrs

In [251]:
np.random.seed(seed= 0)# if you set a seed the computer will always generate the random  numbers along with the seed
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [252]:
np.random.seed(seed=1)
numbers = pd.DataFrame(np.random.uniform(10,size=(5,3)) * 10,
                       columns=["a","b", "c"])
numbers

a          b          c
0  62.468020  35.170796  99.989706
1  72.790068  86.791970  91.689526
2  83.236581  68.899535  64.290927
3  51.506494  62.272494  38.330245
4  81.599298  20.969431  97.535117

In [253]:
import array
l = [i for i in range(10)]
a = array.array("i", l)

In [254]:
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [255]:
np.array([1,2.,3,4,5])

array([1., 2., 3., 4., 5.])

In [256]:
np.array([range(i , i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [257]:
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [258]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [259]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [260]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [261]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Fiding uniq numbers in an array

In [262]:
random_array_5 = np.array([1,1,1,2,3,4,5,4,7,9,9])
random_array_5
np.unique(random_array_5)   # it returns the uniq values that are only on in the NdArray

array([1, 2, 3, 4, 5, 7, 9])

# 3. Viewing aarrays and matrices

In [263]:
a1

array([1, 2, 3])

In [264]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [265]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [266]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [267]:
a2[:2, :2]

array([[1., 2.],
       [4., 5.]])

In [268]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))# try to undrestand the size

In [269]:
a4#

array([[[[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1],
         [0, 1, 8, 8, 3]],

        [[9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4],
         [8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9]],

        [[2, 7, 7, 9, 8],
         [6, 9, 3, 7, 7],
         [4, 5, 9, 3, 6],
         [8, 0, 2, 7, 7]]],


       [[[9, 7, 3, 0, 8],
         [7, 7, 1, 1, 3],
         [0, 8, 6, 4, 5],
         [6, 2, 5, 7, 8]],

        [[4, 4, 7, 7, 4],
         [9, 0, 2, 0, 7],
         [1, 7, 9, 8, 4],
         [0, 1, 9, 8, 2]],

        [[3, 1, 2, 7, 2],
         [6, 0, 9, 2, 6],
         [6, 2, 7, 7, 0],
         [6, 5, 1, 4, 6]]]])

In [270]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [271]:
#Get the first 4 numbers in the inner most array

In [272]:
a4[:, :, :, :4]

array([[[[2, 4, 7, 7],
         [1, 7, 0, 6],
         [9, 7, 6, 9],
         [0, 1, 8, 8]],

        [[9, 8, 7, 3],
         [5, 1, 9, 3],
         [8, 1, 4, 0],
         [9, 2, 0, 4]],

        [[2, 7, 7, 9],
         [6, 9, 3, 7],
         [4, 5, 9, 3],
         [8, 0, 2, 7]]],


       [[[9, 7, 3, 0],
         [7, 7, 1, 1],
         [0, 8, 6, 4],
         [6, 2, 5, 7]],

        [[4, 4, 7, 7],
         [9, 0, 2, 0],
         [1, 7, 9, 8],
         [0, 1, 9, 8]],

        [[3, 1, 2, 7],
         [6, 0, 9, 2],
         [6, 2, 7, 7],
         [6, 5, 1, 4]]]])

In [273]:
a4[:, :, :, :1]

array([[[[2],
         [1],
         [9],
         [0]],

        [[9],
         [5],
         [8],
         [9]],

        [[2],
         [6],
         [4],
         [8]]],


       [[[9],
         [7],
         [0],
         [6]],

        [[4],
         [9],
         [1],
         [0]],

        [[3],
         [6],
         [6],
         [6]]]])

In [274]:
a4[:, :, :2, :3]

array([[[[2, 4, 7],
         [1, 7, 0]],

        [[9, 8, 7],
         [5, 1, 9]],

        [[2, 7, 7],
         [6, 9, 3]]],


       [[[9, 7, 3],
         [7, 7, 1]],

        [[4, 4, 7],
         [9, 0, 2]],

        [[3, 1, 2],
         [6, 0, 9]]]])

# 4. Manipulating & comparing arrays

## Arithmetic

In [275]:
a1

array([1, 2, 3])

In [276]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [277]:
a1 + ones

array([2., 3., 4.])

In [278]:
a1 - ones

array([0., 1., 2.])

In [279]:
a1 * ones

array([1., 2., 3.])

In [280]:
a2 

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [281]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [282]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [283]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [284]:
# How can you reshape a2 to be compatible with a3?
# search how to reshape numpy array?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a5 = np.array([[1,2,3], [4,5,6]])
a5

In [ ]:
a5.shape

In [ ]:
a5.reshape(3,2)

In [ ]:
a2.shape, a3.shape

In [ ]:
a2.reshape(2,3)

In [ ]:
a2 * a3

In [ ]:
a1 / ones

In [ ]:
# Flooe division... removes the decimals(rounds down)
a2 // a1

In [ ]:
a2 / a1

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1 , ones) == a1 + ones

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
a2 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

## Aggregation

Aggregation = performing the same operatrion on a numer of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1, a2

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use pythons methods(Sum()) on python data types and use NumPy methods(np.sum()) on NumPy

In [ ]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array

In [ ]:
# %timeit checlks how long a particular line of code takes to run
%timeit sum(massive_array)    # Python's method    sum()
%timeit np.sum(massive_array) # NumPy's method     np.sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.mean(a2)

In [ ]:
# standard deviation = a measure of how spreade out a group of numbers is from the mean
# 
np.std(a2)

In [ ]:
# variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance =  lower range of numbers
np.var(a2)

In [ ]:
# standard devision = square root of variance
np.sqrt(np.var(a2))

In [ ]:
datafram = pd.DataFrame(np.random.randint(1,10, size=(5, 3)), columns=['a', 'b', 'c'])

In [ ]:
datafram

## Reshaping & transposing

In [ ]:
a2

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2_reshaped = a2.reshape((2,3,1)).shape

In [ ]:
a3.shape

In [ ]:
a3 * a2_reshaped 

In [ ]:
# TransPose = switches the axis'
a2.T.shape

In [ ]:
a2.T.T

In [ ]:
a3.shape

In [ ]:
a3.T.shape

## Dot Product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))
mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Elemnt-Wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot Product
np.dot(mat1, mat2 )

In [ ]:
mat3 = np.dot(mat1, mat2.T) 

In [ ]:
mat3

### Dot Products examples (Nut butter sales)

In [309]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [310]:
mon = np.array([2, 7, 1])
tues = np.array([9, 4, 16])
wed = np.array([11, 14, 18])
thurs = np.array([13, 13, 9])
fri = np.array([15, 18, 9])

In [311]:
price = np.array([10, 8, 12])

In [312]:
sales = pd.DataFrame([mon, tues, wed, thurs, fri], columns=("Almond", "peanut", "cashew"), index=("Mon", "Tues", "Wed","Thurs","Fri"))

In [313]:
sales

Almond  peanut  cashew
Mon         2       7       1
Tues        9       4      16
Wed        11      14      18
Thurs      13      13       9
Fri        15      18       9

In [314]:
sales["Total ($)"] = np.dot(sales, price)

In [316]:
sales

Almond  peanut  cashew  Total ($)
Mon         2       7       1         88
Tues        9       4      16        314
Wed        11      14      18        438
Thurs      13      13       9        342
Fri        15      18       9        402

### Comparrision Operators

In [317]:
a1

array([1, 2, 3])

In [318]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [319]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [322]:
bool_arraya = a1 >= a2
bool_arraya

array([[ True,  True, False],
       [False, False, False]])

In [323]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

 # 5. Sorting

In [325]:
random_array = np.random.randint(10, size=(3,5))

In [326]:
random_array

array([[9, 3, 9, 1, 4],
       [4, 6, 8, 8, 9],
       [2, 7, 5, 5, 4]])

In [327]:
random_array.shape

(3, 5)

In [328]:
np.sort(random_array)

array([[1, 3, 4, 9, 9],
       [4, 6, 8, 8, 9],
       [2, 4, 5, 5, 7]])

In [329]:
np.argsort(random_array)

array([[3, 1, 4, 0, 2],
       [0, 1, 2, 3, 4],
       [0, 4, 2, 3, 1]], dtype=int64)

In [330]:
a1

array([1, 2, 3])

In [331]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [334]:
np.argmin(a1)

0

In [335]:
np.argmax(a1)

2

In [337]:
np.argmax(random_array, axis=0)

array([0, 2, 0, 1, 1], dtype=int64)

In [338]:
np.argmax(random_array, axis=1)

array([0, 4, 1], dtype=int64)

# 6. Practical Examples - NumPy in Action!!!  

In [340]:
# panda image in the numpy images...

## Turning images into NumPy array

In [342]:
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [344]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [345]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [346]:
# Car
car = imread("car-photo.png")

In [347]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [348]:
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

In [349]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [350]:
# Dog
dog = imread("dog-photo.png")
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [351]:
print(type(dog))

<class 'numpy.ndarray'>
